### ISSUE TITLE
Exception when converting from .nnue to .pt with serialize.py "Exception: Expected: 7af32f20, got 6d74683c"

### ISSUE THREAD

**Issue by kennyfrc** [glinscott/nnue-pytorch#136]
I have tried to convert the two most recent master nets, "nn-3475407dc199.nnue" and "nn-190f102a22c3.nnue" into .pt files with the two following commands:

```
 python3 serialize.py nn-3475407dc199.nnue nn-3475407dc199.pt --features=HalfKAv2
```

and

```
 python3 serialize.py nn-3475407dc199.nnue nn-3475407dc199.pt --features=HalfKAv2^
```

both failed with the following error:
```
Converting nn-3475407dc199.nnue to nn-3475407dc199.pt
Traceback (most recent call last):
  File "serialize.py", line 242, in <module>
    main()
  File "serialize.py", line 225, in main
    reader = NNUEReader(f, feature_set)
  File "serialize.py", line 139, in __init__
    self.read_header(feature_set, fc_hash)
  File "serialize.py", line 158, in read_header
    self.read_int32(VERSION) # version
  File "serialize.py", line 203, in read_int32
    raise Exception("Expected: %x, got %x" % (expected, v))
Exception: Expected: 7af32f20, got 6d74683c
```

When I try to convert .nnue files to .pt generated on my local machine, it is successful with `--features=HalfKAv2`. Here is a link to the .nnue file that worked for me: https://drive.google.com/file/d/1qBO_nEZEaucLlvdrhBkibPFbKv5ifHHR/view?usp=sharing

**Comment by Sopel97** [comment]
Unable to replicate with the latest master:
```
C:\dev\nnue-pytorch>python serialize.py nn-190f102a22c3.nnue nn.pt --features=HalfKAv2
Converting nn-190f102a22c3.nnue to nn.pt

C:\dev\nnue-pytorch>python serialize.py nn-3475407dc199.nnue nn.pt --features=HalfKAv2
Converting nn-3475407dc199.nnue to nn.pt

```
