### ISSUE TITLE
visualize.py fails on current arch .nnue

### ISSUE THREAD

**Issue by vondele** [glinscott/nnue-pytorch#188]

**Comment by vondele** [comment]
```
Traceback (most recent call last):
  File "visualize.py", line 580, in <module>
    main()
  File "visualize.py", line 545, in main
    model = load_model(args.model, feature_set)
  File "visualize.py", line 465, in load_model
    reader = NNUEReader(f, feature_set)
  File "/home/vondele/chess/vondele/nnue-pytorch/serialize.py", line 149, in __init__
    self.read_feature_transformer(self.model.input, self.model.num_psqt_buckets)
  File "/home/vondele/chess/vondele/nnue-pytorch/serialize.py", line 184, in read_feature_transformer
    weights = self.tensor(numpy.int16, [shape[0], shape[1]-num_psqt_buckets])
  File "/home/vondele/chess/vondele/nnue-pytorch/serialize.py", line 176, in tensor
    d = d.reshape(shape)
RuntimeError: shape '[23296, 1024]' is invalid for input of size 23499680
```

**Comment by movepicker** [comment]
i suggest that change shape size to `[30880,761]`
