### ISSUE TITLE
train.py issue 

### ISSUE THREAD

**Issue by brainwant** [glinscott/nnue-pytorch#204]
python train.py --smart-fen-skipping --random-fen-skipping 3 --batch-size 16384 --threads 2 --num-workers 2 --gpus 1 trainingdata validationdata
Traceback (most recent call last):
  File "C:\Users\bsryc\Desktop\nnue-pytorch-master\train.py", line 149, in <module>
    main()
  File "C:\Users\bsryc\Desktop\nnue-pytorch-master\train.py", line 63, in main
    raise Exception('{0} does not exist'.format(args.train))
Exception: trainingdata does not exist

**Comment by Sopel97** [comment]
You did not specify correct training and validation data files. See https://github.com/glinscott/nnue-pytorch/wiki/Training-datasets
