### ISSUE TITLE
serialize with --features=HalfKP no longer works

### ISSUE THREAD

**Issue by jdart1** [glinscott/nnue-pytorch#234]
This used to work but no longer does. It looks like it now assumes there are PSQT features. 
There may be other dependencies on a PSQT-enabled network, for example in the trainer.
```
jdart@bunny:~/chess/nnue-pytorch$ python3 serialize.py --features=HalfKP arasan-d10-20220723.nnue arasan-d10-20220723.pt
Converting arasan-d10-20220723.nnue to arasan-d10-20220723.pt
Traceback (most recent call last):
  File "/home/jdart/chess/nnue-pytorch/serialize.py", line 253, in <module>
    main()
  File "/home/jdart/chess/nnue-pytorch/serialize.py", line 236, in main
    reader = NNUEReader(f, feature_set)
  File "/home/jdart/chess/nnue-pytorch/serialize.py", line 144, in __init__
    self.model = M.NNUE(feature_set)
  File "/home/jdart/chess/nnue-pytorch/model.py", line 162, in __init__
    self._init_layers()
  File "/home/jdart/chess/nnue-pytorch/model.py", line 177, in _init_layers
    self._init_psqt()
  File "/home/jdart/chess/nnue-pytorch/model.py", line 185, in _init_psqt
    initial_values = self.feature_set.get_initial_psqt_features()
  File "/home/jdart/chess/nnue-pytorch/feature_set.py", line 119, in get_initial_psqt_features
    init += feature.get_initial_psqt_features()
  File "/home/jdart/chess/nnue-pytorch/halfkp.py", line 33, in get_initial_psqt_features
    raise Exception('Not supported yet. See HalfKA')
Exception: Not supported yet. See HalfKA
```

**Comment by xu-shawn** [comment]
HalfKP support has been removed since #397
