### ISSUE TITLE
RuntimeError: Pinned memory requires CUDA

### ISSUE THREAD

**Issue by vshcherbyna** [glinscott/nnue-pytorch#36]
Hello,

Thanks for very interesting project and contributing to NNUE training.

I am trying to use the trainer for Igel and when running the test command:

```
python train.py total_3m_d14.bin total_3m_d16_nnue.bin --lambda 1.0 --val_check_interval 2000 --threads 2 --batch-size 16384 --progress_bar_refresh_rate 20
```

I got an error: 

```
RuntimeError: Pinned memory requires CUDA. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason.  The CUDA library MUST be loaded, EVEN IF you don't directly use any symbols from the CUDA library! One common culprit is a lack of -INCLUDE:?warp_size@cuda@at@@YAHXZ in your link arguments; many dynamic linkers will delete dynamic library dependencies if you don't depend on any of their symbols.  You can check if this has occurred by using link on your binary to see if there is a dependency on *_cuda.dll library.
```

I am running Windows 10 and I installed CUDA. Full output of the command is below:

```
(env) C:\Users\volodymyr\Documents\Sources\nnue-pytorch>python train.py total_3m_d14.bin total_3m_d16_nnue.bin --lambda 1.0 --val_check_interval 2000 --threads 2 --batch-size 16384 --progress_bar_refresh_rate 20
Feature set: HalfKP^
Num real features: 41024
Num virtual features: 704
Num features: 41728
Training with total_3m_d14.bin validating with total_3m_d16_nnue.bin
Seed 42
Using batch size 16384
Smart fen skipping: False
Random fen skipping: 0
limiting torch to 2 threads.
Using log dir logs/
C:\Users\volodymyr\Documents\Sources\nnue-pytorch\env\lib\site-packages\pytorch_lightning\utilities\distributed.py:49: UserWarning: ModelCheckpoint(save_last=True, monitor=None) is a redundant configuration. You can save the last checkpoint with ModelCheckpoint(save_top_k=None, monitor=None).
  warnings.warn(*args, **kwargs)
GPU available: False, used: False
TPU available: None, using: 0 TPU cores
Using c++ data loader
Ranger optimizer loaded.
Gradient Centralization usage = True
GC applied to both conv and fc layers

  | Name   | Type   | Params
----------------------------------
0 | input  | Linear | 10.7 M
1 | l1     | Linear | 16.4 K
2 | l2     | Linear | 1.1 K
3 | output | Linear | 33
----------------------------------
10.7 M    Trainable params
0         Non-trainable params
10.7 M    Total params
Validation sanity check: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "train.py", line 99, in <module>
    main()
  File "train.py", line 96, in main
    trainer.fit(nnue, train, val)
  File "C:\Users\volodymyr\Documents\Sources\nnue-pytorch\env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 470, in fit
    results = self.accelerator_backend.train()
  File "C:\Users\volodymyr\Documents\Sources\nnue-pytorch\env\lib\site-packages\pytorch_lightning\accelerators\cpu_accelerator.py", line 62, in train
    results = self.train_or_test()
  File "C:\Users\volodymyr\Documents\Sources\nnue-pytorch\env\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 69, in train_or_test
    results = self.trainer.train()
  File "C:\Users\volodymyr\Documents\Sources\nnue-pytorch\env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 492, in train
    self.run_sanity_check(self.get_model())
  File "C:\Users\volodymyr\Documents\Sources\nnue-pytorch\env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 690, in run_sanity_check
    _, eval_results = self.run_evaluation(test_mode=False, max_batches=self.num_sanity_val_batches)
  File "C:\Users\volodymyr\Documents\Sources\nnue-pytorch\env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 593, in run_evaluation
    for batch_idx, batch in enumerate(dataloader):
  File "C:\Users\volodymyr\Documents\Sources\nnue-pytorch\env\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "C:\Users\volodymyr\Documents\Sources\nnue-pytorch\env\lib\site-packages\torch\utils\data\dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\volodymyr\Documents\Sources\nnue-pytorch\env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 46, in fetch
    data = self.dataset[possibly_batched_index]
  File "C:\Users\volodymyr\Documents\Sources\nnue-pytorch\nnue_dataset.py", line 151, in __getitem__
    return next(self.iter)
  File "C:\Users\volodymyr\Documents\Sources\nnue-pytorch\nnue_dataset.py", line 89, in __next__
    tensors = v.contents.get_tensors(self.device)
  File "C:\Users\volodymyr\Documents\Sources\nnue-pytorch\nnue_dataset.py", line 32, in get_tensors
    white_values = torch.from_numpy(np.ctypeslib.as_array(self.white_values, shape=(self.num_active_white_features,))).pin_memory().to(device=device, non_blocking=True)
RuntimeError: Pinned memory requires CUDA. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason.  The CUDA library MUST be loaded, EVEN IF you don't directly use any symbols from the CUDA library! One common culprit is a lack of -INCLUDE:?warp_size@cuda@at@@YAHXZ in your link arguments; many dynamic linkers will delete dynamic library dependencies if you don't depend on any of their symbols.  You can check if this has occurred by using link on your binary to see if there is a dependency on *_cuda.dll library.
```

Thanks for any help or hint for the issue.
With best regards,
Volodymyr

**Comment by vondele** [comment]
can you try adding --gpus 1 to the command line (assuming you have a GPU) ?

**Comment by vshcherbyna** [comment]
Thanks @vondele for a quick reply. I don't have GPU available on this machine, so it fails. But I am now going to install the same tooling on the machine with GPU to try the test.

**Comment by vshcherbyna** [comment]
I tried with --gpus 1, it fails saying no gpu is detected which is strange as machine has NVIDIA Quadro RTX card.

```
(env) C:\Users\vshcherbyna\Documents\Tools\other\nnue-pytorch>python train.py total_3m_d14.bin total_3m_d16_nnue.bin --lambda 1.0 --val_check_interval 2000 --threads 2 --batch-size 16384 --progress_bar_refresh_rate 20 --gpus 1
Feature set: HalfKP^
Num real features: 41024
Num virtual features: 704
Num features: 41728
Training with total_3m_d14.bin validating with total_3m_d16_nnue.bin
Seed 42
Using batch size 16384
Smart fen skipping: False
Random fen skipping: 0
limiting torch to 2 threads.
Using log dir logs/
C:\Users\vshcherbyna\Documents\Tools\other\nnue-pytorch\env\lib\site-packages\pytorch_lightning\utilities\distributed.py:49: UserWarning: ModelCheckpoint(save_last=True, monitor=None) is a redundant configuration. You can save the last checkpoint with ModelCheckpoint(save_top_k=None, monitor=None).
  warnings.warn(*args, **kwargs)
Traceback (most recent call last):
  File "train.py", line 99, in <module>
    main()
  File "train.py", line 85, in main
    trainer = pl.Trainer.from_argparse_args(args, callbacks=[checkpoint_callback], logger=tb_logger)
  File "C:\Users\vshcherbyna\Documents\Tools\other\nnue-pytorch\env\lib\site-packages\pytorch_lightning\trainer\properties.py", line 153, in from_argparse_args
    return argparse_utils.from_argparse_args(cls, args, **kwargs)
  File "C:\Users\vshcherbyna\Documents\Tools\other\nnue-pytorch\env\lib\site-packages\pytorch_lightning\utilities\argparse_utils.py", line 50, in from_argparse_args
    return cls(**trainer_kwargs)
  File "C:\Users\vshcherbyna\Documents\Tools\other\nnue-pytorch\env\lib\site-packages\pytorch_lightning\trainer\connectors\env_vars_connector.py", line 41, in overwrite_by_env_vars
    return fn(self, **kwargs)
  File "C:\Users\vshcherbyna\Documents\Tools\other\nnue-pytorch\env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 357, in __init__
    deterministic,
  File "C:\Users\vshcherbyna\Documents\Tools\other\nnue-pytorch\env\lib\site-packages\pytorch_lightning\accelerators\accelerator_connector.py", line 101, in on_trainer_init
    self.trainer.data_parallel_device_ids = device_parser.parse_gpu_ids(self.trainer.gpus)
  File "C:\Users\vshcherbyna\Documents\Tools\other\nnue-pytorch\env\lib\site-packages\pytorch_lightning\utilities\device_parser.py", line 78, in parse_gpu_ids
    gpus = _sanitize_gpu_ids(gpus)
  File "C:\Users\vshcherbyna\Documents\Tools\other\nnue-pytorch\env\lib\site-packages\pytorch_lightning\utilities\device_parser.py", line 142, in _sanitize_gpu_ids
    """)
pytorch_lightning.utilities.exceptions.MisconfigurationException:
                You requested GPUs: [0]
                But your machine only has: []
```

**Comment by vshcherbyna** [comment]
P.S. I also did a reboot of a machine and the result is the same.

**Comment by vshcherbyna** [comment]
As per answer from https://stackoverflow.com/questions/62359175/pytorch-says-that-cuda-is-not-available:

```
PyTorch doesn't use the system's CUDA library. When you install PyTorch using the precompiled binaries using either pip or conda it is shipped with a copy of the specified version of the CUDA library which is installed locally. In fact, you don't even need to install CUDA on your system to use PyTorch with CUDA support.
```

So everything should be shipped when it comes to CUDA support as I am using pip. I wonder if some one can share their python and torch version, I think I can enforce that and just try.

**Comment by vondele** [comment]
```
$ python --version
Python 3.8.5
```
```
NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0
```
```
$ pip list | grep torch
pytorch-lightning      1.0.6    
torch                  1.7.0    
```

**Comment by glinscott** [comment]
You might want to try similar debugging steps as in this issue: https://stackoverflow.com/questions/62359175/pytorch-says-that-cuda-is-not-available.

One note is that there is a CUDA version of pytorch that needs to be installed.

**Comment by vshcherbyna** [comment]
Thanks for all your comments. I made it (almost) work, he solution was:

1. Install latest python 3.9 (I had 3.7), but it still did not work after python upgrade
2. Install pytorch bundled with CUDA from offricial page: https://pytorch.org/get-started/locally/ . I selected my cuda version, pip, windows and then it asked me to execute:

```
pip install torch===1.7.1+cu110 torchvision===0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
```

I run this inside venv, it downloaded 2 GB file and it without factorizer it works:

```
python train.py total_3m_d14.bin total_3m_d16_nnue.bin --lambda 1.0 --val_check_interval 2000 --threads 8 --batch-size 16384 --progress_bar_refresh_rate 20 --gpus 1
```

but when I pass --enable-factorizer it fails:

```
(env) C:\Users\vshcherbyna\Documents\Tools\other\nnue-pytorch>python train.py total_3m_d14.bin total_3m_d16_nnue.bin --lambda 1.0 --val_check_interval 2000 --threads 8 --batch-size 16384 --progress_bar_refresh_rate 20 --gpus 1 --enable-factorizer
usage: train.py [-h] [--logger [LOGGER]] [--checkpoint_callback [CHECKPOINT_CALLBACK]]
                [--default_root_dir DEFAULT_ROOT_DIR] [--gradient_clip_val GRADIENT_CLIP_VAL]
                [--process_position PROCESS_POSITION] [--num_nodes NUM_NODES] [--num_processes NUM_PROCESSES]
                [--gpus GPUS] [--auto_select_gpus [AUTO_SELECT_GPUS]] [--tpu_cores TPU_CORES]
                [--log_gpu_memory LOG_GPU_MEMORY] [--progress_bar_refresh_rate PROGRESS_BAR_REFRESH_RATE]
                [--overfit_batches OVERFIT_BATCHES] [--track_grad_norm TRACK_GRAD_NORM]
                [--check_val_every_n_epoch CHECK_VAL_EVERY_N_EPOCH] [--fast_dev_run [FAST_DEV_RUN]]
                [--accumulate_grad_batches ACCUMULATE_GRAD_BATCHES] [--max_epochs MAX_EPOCHS]
                [--min_epochs MIN_EPOCHS] [--max_steps MAX_STEPS] [--min_steps MIN_STEPS]
                [--limit_train_batches LIMIT_TRAIN_BATCHES] [--limit_val_batches LIMIT_VAL_BATCHES]
                [--limit_test_batches LIMIT_TEST_BATCHES] [--val_check_interval VAL_CHECK_INTERVAL]
                [--flush_logs_every_n_steps FLUSH_LOGS_EVERY_N_STEPS] [--log_every_n_steps LOG_EVERY_N_STEPS]
                [--accelerator ACCELERATOR] [--sync_batchnorm [SYNC_BATCHNORM]] [--precision PRECISION]
                [--weights_summary WEIGHTS_SUMMARY] [--weights_save_path WEIGHTS_SAVE_PATH]
                [--num_sanity_val_steps NUM_SANITY_VAL_STEPS] [--truncated_bptt_steps TRUNCATED_BPTT_STEPS]
                [--resume_from_checkpoint RESUME_FROM_CHECKPOINT] [--profiler [PROFILER]] [--benchmark [BENCHMARK]]
                [--deterministic [DETERMINISTIC]] [--reload_dataloaders_every_epoch [RELOAD_DATALOADERS_EVERY_EPOCH]]
                [--auto_lr_find [AUTO_LR_FIND]] [--replace_sampler_ddp [REPLACE_SAMPLER_DDP]]
                [--terminate_on_nan [TERMINATE_ON_NAN]] [--auto_scale_batch_size [AUTO_SCALE_BATCH_SIZE]]
                [--prepare_data_per_node [PREPARE_DATA_PER_NODE]] [--plugins PLUGINS] [--amp_backend AMP_BACKEND]
                [--amp_level AMP_LEVEL] [--distributed_backend DISTRIBUTED_BACKEND]
                [--automatic_optimization [AUTOMATIC_OPTIMIZATION]] [--move_metrics_to_cpu [MOVE_METRICS_TO_CPU]]
                [--enable_pl_optimizer [ENABLE_PL_OPTIMIZER]] [--py-data] [--lambda LAMBDA_]
                [--num-workers NUM_WORKERS] [--batch-size BATCH_SIZE] [--threads THREADS] [--seed SEED]
                [--smart-fen-skipping] [--random-fen-skipping RANDOM_FEN_SKIPPING]
                [--resume-from-model RESUME_FROM_MODEL] [--features FEATURES]
                train val
train.py: error: unrecognized arguments: --enable-factorizer
```

**Comment by Sopel97** [comment]
Use `--features=HalfKP^` instead of `--enable-factorizer`.

**Comment by vshcherbyna** [comment]
Thanks @Sopel97, it all works as expected. I will close the ticket.
